### PR TITLE
Documentation/guidelines and rules

### PR DESCRIPTION
**Pull request by BernhardSchuld**
This is merely a first draft and is subject to change

### CODE REVIEW

**Review by ClaudeGreeff — APPROVED** [review]
Thorough explanation addressing most/all issues we had discussed. Thanks Bernhard.

**Review by Mazz1es — APPROVED** [review]
Looks good, thanks for setting up the rules.

**Comment by PeteElite** [comment]
Seems good to me. Nice man.

**Review by PeteElite — APPROVED** [review]

**Review by sjohandup — APPROVED** [review]
I'm happy XD

**Pull request merged**
